# Generated by Django 4.2.1 on 2023-05-05 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'title',
                    models.CharField(max_length=256, verbose_name='Title'),
                ),
                ('description', models.TextField(verbose_name='Description')),
                (
                    'is_published',
                    models.BooleanField(
                        default=False, verbose_name='Is Published'
                    ),
                ),
                (
                    'order',
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name='order'
                    ),
                ),
                ('video', models.URLField()),
                ('video_duration', models.FloatField(null=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LessonRelation',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created',
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name='Creation Date and Time',
                    ),
                ),
                (
                    'modified',
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name='Modification Date and Time',
                    ),
                ),
                ('done', models.BooleanField(default=False)),
                (
                    'course',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='lesson_relations',
                        to='course.course',
                    ),
                ),
            ],
        ),
    ]
