# Generated by Django 4.2.1 on 2023-05-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='video_duration',
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_duration_in_seconds',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
