# Generated by Django 4.2.1 on 2023-05-18 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0005_lesson_created_lesson_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonrelation',
            name='course',
        ),
    ]
