# Generated by Django 4.2.1 on 2023-05-31 15:13

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0005_alter_answer_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='level',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='lft',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='parent',
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='children',
                to='answer.answer',
            ),
        ),
        migrations.AddField(
            model_name='answer',
            name='rght',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='tree_id',
            field=models.PositiveIntegerField(
                db_index=True, default=0, editable=False
            ),
            preserve_default=False,
        ),
    ]
