# Generated by Django 4.2.1 on 2023-05-05 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0002_initial'),
        ('module', '0001_initial'),
        ('quiz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quizrelation',
            name='creator',
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name='creator',
            ),
        ),
        migrations.AddField(
            model_name='quizrelation',
            name='quiz',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz'
            ),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='course',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='questions_quiz',
                to='course.course',
            ),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='quiz',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='questions',
                to='quiz.quiz',
            ),
        ),
        migrations.AddField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='quizzes',
                to='course.course',
            ),
        ),
        migrations.AddField(
            model_name='quiz',
            name='module',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='quizzes',
                to='module.module',
            ),
        ),
        migrations.AddConstraint(
            model_name='quizrelation',
            constraint=models.UniqueConstraint(
                fields=('creator', 'quiz'), name='unique quiz relation'
            ),
        ),
    ]
