# Generated by Django 4.2.1 on 2023-05-05 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created',
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name='Creation Date and Time',
                    ),
                ),
                (
                    'modified',
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name='Modification Date and Time',
                    ),
                ),
                (
                    'title',
                    models.CharField(max_length=256, verbose_name='Title'),
                ),
                ('description', models.TextField(verbose_name='Description')),
                (
                    'is_published',
                    models.BooleanField(
                        default=False, verbose_name='Is Published'
                    ),
                ),
                ('slug', models.SlugField(unique=True)),
                (
                    'language',
                    models.CharField(max_length=155, verbose_name='Language'),
                ),
                (
                    'requirements',
                    models.TextField(verbose_name='Requirements'),
                ),
                (
                    'what_you_will_learn',
                    models.TextField(verbose_name='What you will learn'),
                ),
                ('level', models.TextField(verbose_name='Course Level')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CourseRelation',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created',
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name='Creation Date and Time',
                    ),
                ),
                (
                    'modified',
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name='Modification Date and Time',
                    ),
                ),
                (
                    'course',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='course.course',
                    ),
                ),
            ],
        ),
    ]
